package dev.zilvis.renginiuoaze.enums;

public enum Type {
    TYPE_KONCERTAI,
    TYPE_KONFERENCIJOS,
    TYPE_SEMINARAI,
    TYPE_MOKYMAI,
    TYPE_SPEKTAKLIAI,
    TYPE_PREMJIEROS,
    TYPE_INICIATYVOS,
    TYPE_SPORTAS,
    TYPE_UZSAKOMI,
    TYPE_PARODOS,
    TYPE_FESTIVALIAI,
    TYPE_KINAS,
    TYPE_MINEJIMAI,
    TYPE_EKSKURSIJOS,
    TYPE_VAIKAMS,
    TYPE_VAKARELIAI
}
